### ISSUE TITLE
Error upon using a command. I.E /f who, /f create [tag]

### ISSUE THREAD

**Issue by ScarOG** [drtshock/HCFProblems#108]
I am having an error (An internal error occurred while attempting to perform this command) I was wondering if there is a way to fix this, my error from the console is this: https://gist.github.com/ScarOG/3e42b2b6cb5471b112e2

**Comment by nsporillo** [comment]
You can't use craftbukkit 1.7r3 with HCF at this time.

**Comment by nsporillo** [comment]
@ScarOG closing this because we do not support that version. Perhaps in the future we could provide compatibility, but that is not planned at this time. Sorry

Check out http://www.spigotmc.org/, you can run a 1.7.x server with HCF just fine, you're just using a build of craftbukkit that doesnt have a change HCF uses.
