### ISSUE TITLE
New faction DTR not starting from 0

### ISSUE THREAD

**Issue by Quizzes** [drtshock/HCFProblems#123]
Basically I've noticed that DTR (when you make a new faction) is instantly set to the max DTR, but if you invite someone it regens to the max DTR.. When you make a new faction (with just you in it) It should NOT start at the max-player-dtr number. It should start from 0.00 and work its way up to the max DTR that faction can have..

**Comment by nsporillo** [comment]
How is this urgent?

It is currently designed to start at 0, and there is a bug where dtr is a super high number when a faction is first created and is then set to the max (built in max dtr check). It's not even that big of a deal, in fact it's almost like a built in protection feature for brand new factions... 2 deaths to become raidable.

**Comment by Quizzes** [comment]
My bad, wasn't really <code>URGENT but i feel that it should be fixed, all HCF servers start from 0 and work its way up, maybe add a config for that? like start-from-max-dtr: true/false?

**Comment by nsporillo** [comment]
Won't add a new config value for that, will just try and fix the bug.. which is an issue with the initial faction dtr (a config value wouldnt address the real issue)

**Comment by clerkk** [comment]
The reason its like this was because it was requested, for solo factions, I remember this being added and is a good addition @nsporillo , Don't remove it.

**Comment by Quizzes** [comment]
@clerkk Like i said, there should be a config value for it. Some people like it, some don't.

**Comment by MoeXIV** [comment]
I'll share my side of this. I do indeed think that this needs to be fixed ASAP. If a player makes a faction with multiple people on "SoTW", they don't have to "play it safe" in the beginning like on every other HCF server because once 1 person dies, you're still fine. 

Issues like this, although not purposely added, merely bugs reduce the hardcore aspects on the plugin; by name being Hardcore Factions.
