### ISSUE TITLE
Click to join bug

### ISSUE THREAD

**Issue by LOOOOOOOL** [drtshock/HCFProblems#145]
I have the f command allowed to be said in chat so f isnt read. This is from me clicking "Click to join!"
http://gyazo.com/c6f9a2bfeabc477d0d9717bf11154cbc

**Comment by nsporillo** [comment]
What is click to join...

**Comment by LOOOOOOOL** [comment]
when someone invites u to their faction, you can hover over the invite message and it says "Click to join".

**Comment by nsporillo** [comment]
So it's not working..?

**Comment by MoeXIV** [comment]
When he clicks it, it simply makes him execute those 3 lines in chat. Maybe add a slash before it for what ever you made in the code?

**Comment by nsporillo** [comment]
It's probably sending those 3 lines because he clicked it three times.

https://github.com/drtshock/Factions/blob/1.6.x/src/main/java/com/massivecraft/factions/cmd/CmdInvite.java#L53

That is the line in question here. 

Very likely this can be fixed with a slight change in configuration, based on what I see there. Experiment with it. When I get a chance i'll do the same.

**Comment by HCFPvP** [comment]
@nsporillo I'd like to see this fixed. Basically, it doesn't have a slash infront of the command.

**Comment by HCFPvP** [comment]
@nsporillo plz reopen
