### ISSUE TITLE
Your Plugin

### ISSUE THREAD

**Issue by LOOOOOOOL** [drtshock/HCFProblems#152]
I'd like to let yo u know that I'm doing EOTW right now and your plugin is the reason why I had to resart 6 times thinking it was something else.

I had to disable /f command for EOTW as when people do like /f show {name}, it lag spikes the server for 3-4 seconds and my TPS became 12 after people constantly did that. 

I've blocked the /f command for now.

**Comment by drtshock** [comment]
no idea what you're getting at

**Comment by LOOOOOOOL** [comment]
no idea what im getting at?
im trying to get u to fix the freakin plugin

**Comment by LOOOOOOOL** [comment]
@drtshock @nsporillo ^^^

**Comment by Lilmac12312** [comment]
@LOOOOOOOL Why don't you just wait like everyone else for their feature to be added and stop bitching.

**Comment by LOOOOOOOL** [comment]
@Lilmac12312 Can you make sense of what you just said? I just posted an issue and he closed it for "no idea what your getting at"....

**Comment by Lilmac12312** [comment]
@LOOOOOOOL Oh it made sense because if it didn't then it wouldn't be correct English, Here, let me help you out since you'r struggling to figure it out on your own. http://prntscr.com/6xvkb2 - You asked them, @drtshock & @nsporillo to fix the plugin yet there is nothing wrong with it. 

Here's a good idea, maybe if you took a timings report and linked both developers, only if thw TPS lag is related to their plugin then link them to it, if not, it's to do with one of your plugins.

And please, I rather not be called a "suck up" to prplz & itsjhalt. They happen to be friends of mine, I've worked for both of them so I think you should get your shit correct before starting a bigger flame.

**Comment by LOOOOOOOL** [comment]
@Lilmac12312 not gonna lie, I didn't even read what you said above as it's way to o long, but all I can say is "What server do you own again? :)"

**Comment by Lilmac12312** [comment]
@LOOOOOOOL I own an Australian HCF server that brings in more likely more than your US server.

**Comment by nsporillo** [comment]
This tracker is not for trash talking other servers or customers, nor is it to trash talk the developers...

It is mind boggling how you can make ridiculous claims such as our plugin lag spikes your server, but don't even provide any sort of useful evidence. A timings report, even if it happened to be the likely case that it's something else, would still be more helpful. 

Tired of spending my time writing out replies to your ridiculous issues on this tracker just to have them not even be read. As if you're too important to read a simple paragraph. Why should I spend my time supporting you and your server when you show absolutely zero regard for me or anyone else who uses this tracker?

**Comment by Doxify** [comment]
^

I'd also like to add this this is not the plugin's fault (obviously). I had my EoTW today and we maxed out at 200 players with no lag, this is either the hardware your server is running or another plugin causing issues.

**Comment by MoeXIV** [comment]
I agree with Dox. The plugin is fine, it's obviously something on your side "LOOOOOOL".
