### ISSUE TITLE
DTR doesn't update in scoreboard unless you type /f who

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#156]
Title.

![image](https://cloud.githubusercontent.com/assets/9636316/7335420/00fe6cfa-eb72-11e4-9b9d-9fd429633bc9.png)

![](https://i.imgur.com/V3WNIyf.png)

**Comment by nsporillo** [comment]
Known issue. Happened went I revamped variables. 

A lot of lag with scoreboards came with updating a factions DTR several times per second because they had multiple people in one faction online at once. So I just removed it until we could figure out a better way to do it. Obviously it's an issue since scoreboards should be as live as possible...
