### ISSUE TITLE
Minimal /f show

### ISSUE THREAD

**Issue by lyzha** [drtshock/HCFProblems#160]
I was thinking about an option when faction are permanent not to show allies, online or offline players or f home coords

**Comment by nsporillo** [comment]
Not all permanent factions are necessarily factions that don't have allies / online / offline / homes, etc.

We used to have a setting that did not show lines in f-show if they didn't really add anything to the output (Printing out an "Online: ", basically just empty lines). But it was removed because it caused a bunch of confusion. Users were wondering why certain lines weren't showing and that was the reason, and since they did not have updated configs, the setting wasn't there.

**Comment by nsporillo** [comment]
Going to convert this ticket into a request for the minimal-f-show feature to come back (not enabled by default)

**Comment by MoeXIV** [comment]
YES!

**Comment by Lotteries** [comment]
ᕙ༼ ◉_◉༽ᕗ :+1:

**Comment by lyzha** [comment]
:+1:
