### ISSUE TITLE
f stuck

### ISSUE THREAD

**Issue by ArchDaWiz** [drtshock/HCFProblems#167]
With f stuck, I'm using build 45 and instead of teleporting the player to a safe place, it teleports them (sometimes) into bases. 

I think the way this needs to become fixed is by making sure the player is teleported somewhere in wilderness.

**Comment by nsporillo** [comment]
![fuckoff](http://puu.sh/huryw/4e38e02a7d.png)

What, does your server not have this fixed yet? So I should fix this and not someone elses issue?

**Comment by ArchDaWiz** [comment]
@nsporillo That is unrelated to this topic. I asked you to make it configurable.

**Comment by ArchDaWiz** [comment]
Update:
Make sure it isn't just some random wildness location. It should be like on the border of the claim there in next to wilderness. But wilderness is the key thing in this.

**Comment by nsporillo** [comment]
@ArchDaWiz it's not unrelated to this topic, you're on your 3rd account demanding I fix bugs *just* for you. You paid $30 for a plugin that is **not just for you**. 

Going out of your way to request something that will obviously be configurable to be configurable is ignorant and annoying. We're tired of dealing with you on this tracker and asked you stay off it for a month but apparently that is too much too ask.

**Comment by ArchDaWiz** [comment]
@nsporillo My friend has a license, can I use his or do I have to buy 1?

**Comment by nsporillo** [comment]
@ArchDaWiz what is the username on the jenkins

**Comment by ArchDaWiz** [comment]
@nsporillo I don't have a license. I can buy one, but I thought I can ask questions on my friends behalf.

1 more question. I'll be able to buy a license in 2 days. Can I post some bugs for you guys to fix, but then you put "No License" till I buy it? I'd like to report 2 more bugs.

**Comment by nsporillo** [comment]
@ArchDaWiz who is your friend?

**Comment by ArchDaWiz** [comment]
@nsporillo Jake.

**Comment by Doxify** [comment]
It's temptingmc...

that'd be my best guess.

**Comment by ArchDaWiz** [comment]
@nsporillo Once he comes online, I'll ask for his jenk name.

**Comment by nsporillo** [comment]
@Doxify that's why my snarky first reply.

@ArchDaWiz If you post issues without a license i'll just tag them as no license, or close them if needed.

**Comment by ArchDaWiz** [comment]
@nsporillo Why are you guys being an ass to so many people? They bought your plugin for god sake. If anything, I want to not buy this anymore. 1st the kid who posted his opinion, then the other guy who asked to make something config. then I asked you guys to make something config. and now tamptingMC?

Anyways,
leave my bug posts open with no license attached until I buy a license (if I do). I'll know if I will in 1-2 days.

**Comment by nsporillo** [comment]
@ArchDaWiz "So many people" = one person who is multi-accounting on github to evade being blocked. Buying the plugin does not mean we need to put up with ridiculous issues and one user in particular who just insults everyones server and demands an in proportion level of support. 

You made your account today, one day after this guy was just blocked again. First thing you do is go and do extremely similar things as the guy who is banned. (Demand something that's going to be configurable, be configurable >.>. Dismiss a fix for something because your server already has a fix for it, etc). 

There is a large volume of support required and actively adding and fixing features is very time consuming. When users such as temptingmc illicit a paragraph reply of explanation and doesn't even read it, it's frustrating. Maybe contrary to others belief, this is not my full time job. I have a limited amount of time to spend on issues and thus having to deal with extremely rude users is annoying.

**Comment by ArchDaWiz** [comment]
@nsporillo relax man, this is minecraft.
just get ur stuff done whenever ur done :dancers:

**Comment by drtshock** [comment]
And another account blocked. Reporting to github.

**Comment by MoeXIV** [comment]
@drtshock how did you figure out it was Tempting other then the similar word had topic choice?
