### ISSUE TITLE
Neutral issue

### ISSUE THREAD

**Issue by lyzha** [drtshock/HCFProblems#168]
When i try to neutral another faction i got that http://prntscr.com/6zcz1g

**Comment by nsporillo** [comment]
What does this section of your config look like:

    max-relations:
      enabled: true
      ally: 2
      truce: 10
      neutral: -1
      enemy: 10

?

**Comment by lyzha** [comment]
max-relations:
  enabled: true
  ally: 2
  truce: 0
  neutral: -1
  enemy: 0

**Comment by nsporillo** [comment]
![one](http://puu.sh/huHsa/35ede828c4.png)
![two](http://puu.sh/huHsz/453337e500.png)

Using the configuration settings you provided, there does not seem to be any issues. 

Not necessarily going to close this issue yet, because I do remember from when I was testing the relation-glitch fix, this happened when max relations were exceeded. However, I would assume since allies work fine, that neutrals would too (no reason they wouldn't, handled the same way).

Setting the label as needs more info, which means try to replicate this issue again and let me know the extra settings and steps you take to replicate it.

**Comment by lyzha** [comment]
Yeah i tried later on and it worked but i had the issue idk why
