### ISSUE TITLE
Mandatory Feature

### ISSUE THREAD

**Issue by SnakeDaoust1232** [drtshock/HCFProblems#2]
You shouldnt be able to kick someone on DTR freeze without paying for it. 

When you type /f kick (player) when you are on DTR freeze, it will notify you that you can kick the player but it will take the dtr that that player has. So say in the config you set it so a player has a max dtr of 1. When someone in your faction dies and you are on dtr freeze, you can kick a player but it will take the 1 dtr away from the factions as if that player died.

Reason: DTR evading
Commands/Messages: /f kick (player) = You are on DTR Freeze, you can wait (time) or use /f forcekick (player) and it will remove (DTRperplayer) from your faction. Be careful!
/f forcekick (player) You have forcekicked (player) from your faction!

**Comment by nsporillo** [comment]
A feature to have DTR removed if a player is kicked can be added, yes.

However, "max-player-dtr" is a little misleading, a players DTR can go above that value in config, heres why.

If you have a faction that's gone raidable, it is possible to have that one person stay on to get the faction back into safety as long as they dont keep dying. It just takes a lot longer. What this also avoids is having your most active players with max dtr, and others in your faction not - this prevents you from hitting your max! very annoying. This is why the system we have in place is just about the only option.

Do you know exactly what happens when you kick someone on DTR freeze? Does DTR stay the same, increase, or decrease? IMO I think it does infact increase if you kick the person who just died from your faction. 

I'll tag this as a bug, and we will add the necessary features to make address this issue.

Thank you for the feedback.

**Comment by SnakeDaoust1232** [comment]
You shouldnt be able to invite players to a faction on DTR freeze. When you kick someone from a faction on DTR freeze the dtr goes down. It does this so people cant prevent themselves from being raidable because if a faction was raidable, they could just kick people and the DTR would go up to a point were they werent raidable. So once again a forcekick = lower dtr. It will take away as much DTR as if someone else were to die in the faction.

**Comment by nsporillo** [comment]
Working on some fixes! :)

**Comment by nsporillo** [comment]
The features requested in this issue were added in full.

Thank you again :smile:
