### ISSUE TITLE
Better scoreboard integration

### ISSUE THREAD

**Issue by KriticalPvP** [drtshock/HCFProblems#242]
So I like the faction scoreboard, and I also use a plugin that has a scoreboard, and I feel that faction scoreboards could be more useful! by adding tags to the factions scoreboard ( Hooks ) for things like enderpearl cooldown, or NexGenKoTHs so we can see all of that shit on the factions scoreboard also Implementation of for CombatTagPlus, this would be greatly appreciated! :)

**Comment by Lilmac12312** [comment]
I mean, this would be good but on the other hand I feel they wont add this but who knows.

**Comment by KriticalPvP** [comment]
Yeah, I don't think they will... :( but It would be nice

**Comment by SaiCoFlu** [comment]
Probably not since this is a factions plugin.

**Comment by KriticalPvP** [comment]
They only have to hook into it?

**Comment by SaiCoFlu** [comment]
But some people don't use that plugin, so that would mean hooking into every single plugin that someone has that uses those features.

**Comment by drtshock** [comment]
The only way we would hook into another plugin for scoreboards is if the it's a large, **publicly* available plugin.

**Comment by KriticalPvP** [comment]
http://dev.bukkit.org/bukkit-plugins/enderpearl-cooldown/

**Comment by HeyImYellow** [comment]
It would conflict with the Factions plugin :P

**Comment by MoeXIV** [comment]
CombatTagPlus. It's already implemented DTR loss on NPC death with HCFactions.

**Comment by MoeXIV** [comment]
FeatherBoard is also a paid resource meaning you have to pay for another plugin to get the full potential for this if it's added :/

**Comment by lyzha** [comment]
I agree with @KriticalPvP and @MoeXIV is adding those two plugins to the scoreboard options would be so nice, the scoreboards are a really huge issue if you're using HCF because hcf and the other plugin gonna create a clash between both plugin's scoreboard and it's gonna disable / prevent one of the plugin from working :(
So, HUGE :+1: for @KriticalPvP

**Comment by KriticalPvP** [comment]
Thanks @lyzha !

**Comment by KriticalPvP** [comment]
@nsporillo Any idea?

**Comment by nsporillo** [comment]
Optimizing the default scoreboard would be the first order of business, since the relation player name tags (over head) rely on it.

Then support for third party plugins may be added, I'm not necessarily opposed unless I need to go way out of my way to integrate. If the author didnt intend on it to be, then I won't bother.

**Comment by nsporillo** [comment]
Added some tags:
Enchancement: We're improving upon the existing scoreboards.
Performance: We need to optimize and improve scoreboards before we add anything to it.
On hold: Currently very busy and wont get to this for a bit.
