### ISSUE TITLE
F stuck is super buggy.

### ISSUE THREAD

**Issue by HeyImYellow** [drtshock/HCFProblems#243]
For me, when any of my players use /f stuck, it doesn't tp them out of the base it literally just tp's them a chunk away from where they were, sometimes it will just glitch out and say teleported to *Their current location of where they typed it* and then it will say the Essentials message after the F Stuck timer has worn out: "Teleportation will commence in 10 seconds."

Why does it do this? Should I just somehow remove Essentials teleport function or?...

Just realised, F Home depends on Essentials so that isn't an option.

**Comment by KriticalPvP** [comment]
It comes with a built in /f home ( doesn't cancel on movement )

**Comment by nsporillo** [comment]
@HeyImYellow what version are you using? The most up to date version will simply search for the nearest wilderness chunk and teleport a player to a relatively safe location there (using essentials safe teleport code, or if ess not installed just tp them to the chunk coords without safety checks). 

The idea is to **not** necessarily teleport them out of a base, but get them to wilderness so they can use /f home or some other command to get out. 

Also, the essentials message is shown because you have a teleport delay inside essentials as well, set the delay in hcf to 0 if you just want it to be the 10 seconds you set in essentials.

**Comment by HeyImYellow** [comment]
Ok, I will try installing the newest version of essentials :)

**Comment by HeyImYellow** [comment]
Or do you mean the newest version of HCFactions?

**Comment by nsporillo** [comment]
hcf

**Comment by HeyImYellow** [comment]
Where can I download the newest version? It isn't updated on MCExchange :O

**Comment by HeyImYellow** [comment]
Do you know where I can find the latest updates?

**Comment by nsporillo** [comment]
@HeyImYellow dev builds are found on the [ci](https://ci.drtshock.net/), make an account if you dont already have one and reply with your username to get access to the hcf builds.

**Comment by HeyImYellow** [comment]
HeyImYellow is my username on the Jenkins.

**Comment by nsporillo** [comment]
@HeyImYellow you should be added. please note that with a username that has caps, you may lose access as the ci tends to reset names to lowercase sometimes (hence the issues on this tracker in the past about that)

If that happens, don't make a new issue just email me at nsporillo@gmail.com

**Comment by HeyImYellow** [comment]
Ok, thankyou :)

Where abouts do I view these builds? :)

**Comment by KriticalPvP** [comment]
@nsporillo can you add me? name = KriticalPvP
