### ISSUE TITLE
Feature Request: /f unfreeze

### ISSUE THREAD

**Issue by Doxify** [drtshock/HCFProblems#26]
I think this command would be useful.

It would take a faction off of dtr freeze.

**Comment by Doxify** [comment]
Is this being added?

**Comment by nsporillo** [comment]
Yes.

**Comment by Surgatations** [comment]
:+1:  Would like this aswell, maybe add a /f freeze to put a faction on freeze? i feel like it would useful in some cases

**Comment by MoeXIV** [comment]
@NauruMC As well to put them out of freeze, due the fact that some may be able to avoid the loss of DTR, which is bannable. Once you set their DTR lower, using the "/f dtr" command, their DTR will just regenerate due to the fact that they're not on freeze.

The command usage could be something like: "/f freeze <faction> [time]". [time] being an optional amount of time, say 59:32, (58 minutes, 32 seconds.). Without the adding of the [time], it either disables the freeze if you have one, or if you don't gives you the default freeze time.

Cheers!

**Comment by nsporillo** [comment]
##### /f thaw <faction> in builds 23 and up.
