### ISSUE TITLE
/f who players kills showing before the player name.

### ISSUE THREAD

**Issue by AlfieC** [drtshock/HCFProblems#275]
Title shows the player's kills before their name, but in the config we have it showing after.

**Comment by AlfieC** [comment]
http://prntscr.com/7fwv1t is a picture.

**Comment by nsporillo** [comment]
This issue was already closed, because it is not a valid way to format. The plugin does not and will not recognize that you want the player kills after every player in the list. It is simply not something we're going to add. The way fancy messages work and how formatting is done, this cannot be achieved without way more work, time, and effort then the features even worth. Being configurable, we have trade-offs, and that is one of them.

 I'm assuming it's like that on some big hcf server like hcteams or kohi, but we're not going well out of our way to copy another server. Sorry

**Comment by AlfieC** [comment]
It wouldn't be 'going out of your way to copy another server' - it's an option that's configurable and it does not work as expected in the config. Is it not possible to simply change the order that the list is output in? To return the name before the kills? It does not appear to be that complicated - even adding in a configurable 'player list suffix' in which we could add in 1 tag would be much better - and would not break anything.

**Comment by MoeXIV** [comment]
The picture you're looking at isn't the kills before every players name, it's the player kills variable before the online variable, MEANING that it only displays before the first person, no one else.

If there's 1 thing I hate its when people tell developers that additions are rather "easy" when they have no Java experience whatsoever.

**Comment by AlfieC** [comment]
MoeXIV: wrong. It works in some places - for example https://i.imgur.com/2Dtegat.png

"If there's 1 thing I hate its when people tell developers that additions are rather "easy" when they have no Java experience whatsoever.".

...no Java experience whatsoever? Please check back in this issue tracker - I've submitted lines of code to improve the plugin, for example the Statistics system which Nick did not even know about himself. 

Whilst we're at it - who are you to judge how 'easy' something is to add when you are not a developer yourself? https://i.imgur.com/WMXpmca.png case and point.

We've actually managed to fix this issue on our HCF server by simply changing the order that the variables are processed in. If Nick wishes to use this, then he is free to, but 'MoeXIV' you are obviously not in any way, shape or form a developer yourself so please refrain from commenting on other people's issues.

**Comment by nsporillo** [comment]
@AlfieC bug fixes are appreciated if you want to push them upstream. I originally closed this because of the nature of FancyMessages.. There is two parts of a line which contains a fancy variable, the prefix and then the actual list of elements (online players, offline, enemies, allies). The prefix is colored and parsed and then the list is appended on to the end of it. 

What I was looking to try and do was parse the string after for example, {online}[{kills}] and parse and append it to the end of each element of the list. This is in the true spirit of our configurable system. It should work for pretty much all variables. This was the concept but I did not find a good way to implement it.

**Comment by AlfieC** [comment]
@nsporillo We didn't do it using 'variables' per se - we simply changed it so instead of returning a player's name it returns the player's name, + how many kills they have. This is specific to our use case, so would be unwise to push this to master - but you could push it + have a 'suffix-names-with-kills: true/false' in config.

**Comment by nsporillo** [comment]
Oh, well yeah see that works but isnt what we're looking to have in the plugin. Shouldn't clutter up the plugin with ad hoc logic, it should just have a more powerful parsing engine lol

**Comment by AlfieC** [comment]
What about a slightly less powerful engine that would simply String.replace("{player_kills}", FPlayer's kills) for the substitution of placeholders? Would be slightly less ad-hoc but still a bit more useful.
