### ISSUE TITLE
/f home Instant Bug

### ISSUE THREAD

**Issue by WFloydBoy** [drtshock/HCFProblems#307]
I have the warmup for /f home set to 10

warmups:
  # Delay for /f home , 0 for none
  f-home: 10
  # Delay for /f warp, 0 for none
  f-warp: 0

However, it seems the plugin completely ignores the f-home value because every time someone does /f home, they instantly teleport. I have changed the value to values ranging from 5-100 and they still teleport instantly.

/f version output: http://gyazo.com/0e64740611a3f9cf05870b5aee1e3681

**Comment by nsporillo** [comment]
I believe the original idea was since essentials also has teleportation warmups built in, if HCF is using essentials for teleporting then we just entirely let essentials handle it. This is to prevent two seperate warmups for a /f home (hcf home warmup + essentials tp warmup) which players would surely complain about.

    // if Essentials teleport handling is enabled and available, pass the teleport off to it (for delay and cooldown)

Therefore, the plugin does completely ignore the HCF f-home warmup. You can disable essentials homes integration in the conf.json by setting `homesTeleportCommandEssentialsIntegration` to false.
