### ISSUE TITLE
Unsupported Characters

### ISSUE THREAD

**Issue by HeyImYellow** [drtshock/HCFProblems#359]
Hello! Quick question as of if it would be easy to implement these characters to work, as of now it gives me these strange looking characters :c

Character I tried: »
  Result:
     http://prnt.sc/8w49oq

Thanks!

**Comment by nsporillo** [comment]
I suspect it is an issue with how you entered the character in the lang file. Possibly with what encoding the lang.yml is saved in. Should be UTF-16 or UTF-32 to properly save those unicode characters.

Alternatively, you could just use the unicode number instead of pasting the actual character into the file.

For example with http://unicode-table.com/en/03BB/, try \u03BB.

There is no issue with the plugin regarding unsupported characters.
