### ISSUE TITLE
Price issue

### ISSUE THREAD

**Issue by BTTP** [drtshock/HCFProblems#361]
I love the plugin but 31 dollars? can it be any cheaper especialy for the up coming holidays ? and why isnt it on spigot? i would like it in my spigot account if possible.

**Comment by nsporillo** [comment]
The plugin is not available on spigot because spigot didn't approve the plugin for sale there.

As far as pricing goes, it geared towards servers that generate revenue and require some amount of support in terms of fixing bugs and adding new features. I don't think the one time cost for a plugin is that high considering any server can add a new game mode to their network relatively easily thanks to HCF.

**Comment by BTTP** [comment]
If u can do 20 ill buy it right now.

**Comment by drtshock** [comment]
no
