### ISSUE TITLE
DTR Question and other questions

### ISSUE THREAD

**Issue by Malvagio87** [drtshock/HCFProblems#374]
Is it possible to disable DTR loss when a player dies standing in a certain Faction (Via config or a hook in the plugin)?

Also are their flags to allow other factions to build within your faction like there is in the mcore version?

Do you have a wiki with all of the commands etc with HCFactions so I can research it on my own and not have to bother you with certain questions?

**Comment by nsporillo** [comment]
It is possible to disable DTR loss when a player dies standing in a certain faction, however it cannot be done natively in HCF. Would need a separate plugin to hook into plugin.

Regarding flags, there exists none currently.

Regarding a wiki, we have a [page](https://github.com/drtshock/HCFProblems/wiki/Permissions-list) on this repository which contains all the permissions HCF uses. No page for commands exists, but you can for the most part match the permission with the command.

If you disable the custom /f help in config.yml, it will list all the commands you can use in page format.

**Comment by Malvagio87** [comment]
What event would you suggest for the hook since there is not realy an FPlayerDeathEvent or DTRChangeEvent with the player that causes the change?

**Comment by nsporillo** [comment]
There is a DTRChangeEvent but you are correct in that it doesn't contain the player who caused it.

However, I can add the necessary code to make what you're looking for possible.

**Comment by Malvagio87** [comment]
that would be great thank you.

can you also add a code or some way to hook to allow players to edit a specified faction id?

**Comment by nsporillo** [comment]
Not sure what you mean by that, can you open a new issue explaining what you're looking for? Once I finish the improved DTRChangeEvent i'll post some documentation about the changes as a comment on this issue and then close it. So if you have additional requests please separate them into individual issues.

Thank you.

**Comment by Malvagio87** [comment]
"Tell him if he does that you would need the player that caused the DTR change, the reason for the change (dying) and the location the player died at. So it would maybe be wise to use a FPlayerDeathEvent which would need a method to cancel DTR change"

What my dev sent me to ask.

**Comment by nsporillo** [comment]
DTRChangeEvent is now a FactionPlayerEvent which means it has a FPlayer associated with it. But only when DTR is changed due to a player dying. The other causes of DTR change (/f dtr or dtr regenerating) will have a null player. Having a "reason change" is unnecessary.

Furthermore, FPlayer exposes a method called getLastStoodAt() which returns an FLocation. This will be useful for determining where the player died since they last stood in the chunk (aka FLocation) of a specific faction (or wilderness) and that doesn't change until they respawn.

**Comment by Malvagio87** [comment]
THANKS A TON!

**Comment by nsporillo** [comment]
no problem, gonna close this issue. The changes will be present in build 68 on the CI.

**Comment by Malvagio87** [comment]
where can i download this build?  I dont see it updated where i purchased it on mcexchange

**Comment by nsporillo** [comment]
I post a build to MCE every now and then (when theres 5-10+ things changed since last build).

Developer builds are found on the CI (Continuous Integration), it is basically a site where I can click Build and it'll compile from the latest source a jar file which those with access can download. 

If you want access you need to make an account on ci.drtshock.net and then email me at nsporillo@gmail.com with your username (exact case, i recommend you dont use caps) and I can add you to the whitelist.

**Comment by Malvagio87** [comment]
awesome thanks ill send you an email now
