### ISSUE TITLE
Safezone

### ISSUE THREAD

**Issue by williambraecky** [drtshock/HCFProblems#378]
Safezone is considered as an enemy zone and because of that commands that are  blocked in enemy claims are blocked

**Comment by nsporillo** [comment]
Can you explain a little bit more? 

There exist 5 separate lists for blocking commands. As follows:

    territoryNeutralDenyCommands
    territoryEnemyDenyCommands
    warzoneDenyCommands
    territoryAllyDenyCommands
    wildernessDenyCommands

You're putting commands in `territoryNeutralDenyCommands`, and those commands are also blocked when players are in safe zones? 

This should be the case in the wilderness since with HCF, default-relation is enemy. But not sure why it's the case with safe zone. 

If possible could you run a quick test and describe the steps you took to verify the issue? Thanks

**Comment by williambraecky** [comment]
This is weird, i changed my servers for testing and territoryenemydenycommands don't even work anymore

**Comment by nsporillo** [comment]
Are you admin bypassing?

Here is a snip:

    if (rel.isEnemy() && !Conf.territoryEnemyDenyCommands.isEmpty() && !me.isAdminBypassing() && isCommandInList(fullCmd, shortCmd, Conf.territoryEnemyDenyCommands.iterator())) {
            me.msg(TL.PLAYER_COMMAND_ENEMY, fullCmd);
            return true;
        }

isCommandInList isn't relevant here, but those are the 4 conditions that go into command control.

**Comment by williambraecky** [comment]
Thank you for those fast answers, the problem did not come from you but from one of my plugins. 
I'm closing this issue, sorry for taking your time.

**Comment by williambraecky** [comment]
Ok, so i finally got my dedicated server, and by testing i found out that Safezone is considered as an enemy territory with default-relation on enemy, this is causing commands to be blocked in safezone.

**Comment by nsporillo** [comment]
Dont re-open an old closed issue under a new title, create a new issue please.
