### ISSUE TITLE
Can't Destroy People's Raidable Land

### ISSUE THREAD

**Issue by SoAaron** [drtshock/HCFProblems#4]
When someone is raidable, it doesn't change anything. You can't ove claim, break their blocks or open chests, etc...

**Comment by SnakeDaoust1232** [comment]
Its true, when the faction is raid able, you break anything or use, or anything :P

**Comment by SoAaron** [comment]
yup :/

**Comment by nsporillo** [comment]
Can you confirm that when their faction DTR is below 0, and raidable appears to be "true", factions actually can't be raided? (breaking blocks, opening chests)

Overclaiming has been removed from this version of factions, it was not considered an HC feature, but if we get enough requests (just a few pretty much) to add it back in, we will.

**Comment by SoAaron** [comment]
Okay, bout to record a video.

**Comment by SoAaron** [comment]
@nsporillo https://www.youtube.com/watch?v=5kHNvWYOHM8&feature=youtu.be

**Comment by nsporillo** [comment]
Appreciate the video, definitely helps out with fixing this issue.

We did test raiding, and it was working fine - that's why we felt confident in the release. Something must have been left out causing this issue, I will be looking into it tonight and into the next few days. 

Please be aware our resource was removed from spigotmc, therefore until we find a resolution, issue fixes may  take longer to be rolled out while we figure out how to get our project out of limbo.
With that said, I'll tag the issue - and make it a priority over other issues as it is game breaking.

Thanks again for the detailed report

**Comment by SoAaron** [comment]
@nsporillo thanks! Will we be able to get a good version of the plugin, as we already bought it?

**Comment by SnakeDaoust1232** [comment]
To respond. Yes the raidable feature isnt working but the "overclaim" feature is not a HCF feature therefore it shouldnt be added.

**Comment by nsporillo** [comment]
@SoAaron Yes, despite our resource being removed, I plan on providing support for this project. I'm a little embarrassed our first release ended up containing game breaking bugs, 

We're still in the process of getting everything up to speed, but YES! you will get a good version of the plugin since you bought it! :+1:

**Comment by nsporillo** [comment]
Found the issue. We changed the config and forgot to remove a check in the player listeners, causing raiding to be perma blocked. 

Closing the issue, as it has been addressed!

**Comment by SoAaron** [comment]
@nsporillo I appreciate the help! in this case, how do we get the good version without rebuying it?

**Comment by drtshock** [comment]
I'll be posting a new way for that soon. Just be patient :)
