### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#64]
Hey, so I have some questions.
1) Can you disable the command /f c t and /f neutral somewhere in the config. as I've set them both to 0?
2) Tab doesn't update: http://i.imgur.com/bnUNK4E.png
3) How do I remove the prefix from the username in tab and above players heads?

Thanks, hope you guys can help me out.

**Comment by nsporillo** [comment]
default-prefix: '[&3{faction}&r]{relationcolor}'

The scoreboards are still a work in progress. We had to include all players as opposed to just players with factions due to default relation being enemy on HCF. This change caused some of the unusual behavior of the scoreboards.

Disable factionOnlyChat in your conf.json.

**Comment by TMNetwork** [comment]
@nsporillo where do i find the default-prefix in?
In, the .yml or .json

**Comment by nsporillo** [comment]
@TMNetwork lang.yml
