### ISSUE TITLE
/f kick whilst on DTR Freeze Bug

### ISSUE THREAD

**Issue by SnakeDaoust1232** [drtshock/HCFProblems#7]
https://www.youtube.com/watch?v=wmJ8OwhtZG4&feature=youtu.be

**Comment by nsporillo** [comment]
What version?

This was a known issue, however it should be fixed in our very latest versions. 
(Which we are still trying to distribute to customers as best as we can right now :grimacing: )

**Comment by RydanMC** [comment]
I believe we are using version 0.0.3.

**Comment by nscwalk** [comment]
When will 0.0.4 be out because 0.0.3 has many bugs like this and DTR going to your maximum set DTR not player DTR

**Comment by nsporillo** [comment]
The fix was already made, it's simply a matter of getting the new builds out to you guys...

I apologize for the excessive delay, I understand it can be quite frustrating to be stuck with a broken build when the fix exists, just not available yet. 

Getting our builds available is my focus, however it's not in my power todo so - so I can only bug who handles the CI until then.

Also, if you dont have access to the CI - contact @drtshock somehow, you're going to need to have an account on the CI and that account given access to view the dev builds. Otherwise you'll see an error and say "Broken link".

**Comment by nscwalk** [comment]
@nsporillo I contacted DRTshock and he said there is no 0.0.4 ver and the CI is broken

**Comment by nsporillo** [comment]
Can you confirm the issue exists in the latest dev build?

**Comment by MoeXIV** [comment]
Yes, it is fixed.

**Comment by nsporillo** [comment]
@MoeXIV Thank you. @nscwalk @SnakeDaoust1232 closing this as solved :smiley:
