### ISSUE TITLE
Permanent factions shouldn't be raidable

### ISSUE THREAD

**Issue by clerkk** [drtshock/HCFProblems#89]
Okay, so I was told to post this here as Trent is busy.
When I want to make a faction permanent, It doesn't allow me to edit its DTR. For example, I have a koth and I claim it, but when I leave the faction, it sets the DTR to 0, meaning people can destroy the land, is there a way to set their DTR higher to prevent this from happening, or is there other ways around this?

**Comment by nsporillo** [comment]
Good issue. This is an example of particular situation that wasn't taken into account when I designed DTR, but is a relatively easy fix and can be useful for all servers running HCF. 

I'm thinking a configurable value for permanent-faction-dtr, which is ONLY used for permanent factions that has 0 players. (normal code just takes # of players * player-dtr, so 0 * whatever is 0 thus raidable)

**Comment by clerkk** [comment]
This would be a great improvement, and server would benefit from it, you could possibly make the factions similar to WarZone/ SafeZone, which you would configure in the config?

**Comment by nsporillo** [comment]
@clerkk 

I don't think a permanent faction that has no players is necessarily the same as a warzone or safezone. The feature requested was just disallow raiding a permanent faction with no players because it's DTR is 0 (because no players). 

If we treated it as a war/safe zone, that could have unintended size effects.

**Comment by drtshock** [comment]
Why not set it as a warzone?

**Comment by NauruMC** [comment]
Because some owners like the message for koths such as

&eLeaving &4Warzone&e, Entering &cKOTHNAME etc..

**Comment by MoeXIV** [comment]
That's not it. It's for accessibility not the entering messages. You claim the KOTH, and all you have to do is "f show <KOTH>" and it gives you the cords of the capture zone.

Easier on players.

**Comment by nsporillo** [comment]
@NauruMC @clerkk @MoeXIV 

Would adding an option to simply make `permanent` factions with `0` members have a DTR of like 0.1 so it's not raidable resolve this issue?

**Comment by clerkk** [comment]
Yeah, that would help it actually. :+1:

**Comment by nsporillo** [comment]
@clerkk good to hear. I figured it'd work because even factions that aren't made with the same idea you had in mind with this issue would be protected from raids if all the members left and it was permanent. 

It was not present in the current design because it was implied that a faction with no members was not a faction at all. (Obviously not true at this point, and during testing that assertion held)

Look for a fix later today, writing this in between one of my classes. :+1:

**Comment by clerkk** [comment]
@nsporillo Any update?

**Comment by nsporillo** [comment]
@clerkk still planned on being added, just havent gotten a chance yet. Sorry about the incorrect estimate.

**Comment by clerkk** [comment]
@nsporillo No problem buddy :)

**Comment by clerkk** [comment]
@nsporillo Would it also be possible, to have a custom /f show for permanent factions? so when its set in-game, it automatically changes to the other style, that is customisable in the config? i.e. remove the basics, like claimed land.

**Comment by KriticalPvP** [comment]
How do you even make Perm Factions? @nsporillo

**Comment by drtshock** [comment]
Please read documentation and stop bumping issues.
