### ISSUE TITLE
DTR Evasion

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#93]
So in HCF, there is an issue with DTR evading. They kick the player right before he dies.

Solution: Make it so if they are in combat, that they cannot be kicked from the fac.

Example:
&cYou cannot kick {name} while he/she is in combat.
 

Make the combat checker configurable in seconds. (No need for in game notifications).

**Comment by NauruMC** [comment]
:+1: I like this, @nsporillo will have to look into this :) This would be helpful!

**Comment by nsporillo** [comment]
Can just change the kick penalty so it penalizes even if a faction is not frozen.

An elaborate combat checker is not only unnecessary but outside the scope of this plugin.

**Comment by TMNetwork** [comment]
The kick penalty isn't like an HCF server. If some people don't know about
it, it can make them raidable. Can you release source or something so I can
have 1 of my devs add this? This is needed

**Comment by MoeXIV** [comment]
Maybe just clocking a timer, with no affect? All you'd have to so is set your combat timer to the same time and your SOLID!

**Comment by nsporillo** [comment]
A better solution would be to just set a variable for f players that doesnt get saved, which holds the date (down to the millesecond) they last took or dealt damage. If we attempt to kick this player and they've been taken / dealt damage in the last x seconds, it doesnt allow it. If the player does die and the faction doesnt go raidable, then we can safely ignore this date so they can be kicked after the faction already absorbs the death-dtr.

This would apply to *all* damage, because if a player is stuck in lava you could just kick them too. PVP is irrelevant in this case unless the player we want to kick just dealt damage to someone (this wont be configurable, we should clear up whether or not we should handle players dealing damage in this issue)

The configurable variable would something like `hcf.dtr.leave-cooldown` and default to 0 which is disabled.

**Comment by MoeXIV** [comment]
Yes, players dealing damage would defiantly have to be added.
When it comes to thinks like Mobs, what if they are grinding, or stealing for example, or inside raising you, you won't be able to kick them if they take the items and keep interacting with a mob. It would be smart to disable the tag starting with mobs. Keep it to just Water, Lava and PVP. Not even fall damage.

**Comment by nsporillo** [comment]
@MoeXIV thanks for the help clearing up how we're going to add this. Just going to leave this issue open until everyone has a chance to post some constructive comments on how this will be added. Not going to dive into it and push something we dont want. That doesnt mean their cant be disagreement though, just need a good idea of what we want to do before I go and do it.

**Comment by nsporillo** [comment]
This was added, will be present in our next build (not available as of this posting, be patient)

Thank you.
