### ISSUE TITLE
REQUEST: Founded Date

### ISSUE THREAD

**Issue by NauruMC** [drtshock/HCFProblems#94]
Basicly, just a neat little feature. There should be a variable such as {createDate} and it will show the date and time the faction was made. Here is a example on a different server.

![a1f271d35b7293d17e17aa65ea41eb9a](https://cloud.githubusercontent.com/assets/9434234/6912095/a80baa24-d738-11e4-9f1e-46d76557c951.png)

**Comment by nsporillo** [comment]
When this is added, there wont be any way of telling when an existing faction was created. Their foundedDate will be 0 (1969..), so whenever the plugin calls the function that returns the founded date, we check if it is 0 and sets it to the current time.

Just wanted to explain how we would handle that case since I can already see issues being made on the this tracker saying that a faction was founded well before what it says in /f show.

**Comment by MoeXIV** [comment]
Can you not just use the date and time of the PC? Not the hour or minute etc, but the month / day?

**Comment by nsporillo** [comment]
@MoeXIV Yes, see http://docs.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html

How date is formatted is controlled by what is in the lang, so just change it in there. If you have any questions let me know
