### ISSUE TITLE
Reopen...

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#95]
Can you guys reopen this?

Like seriously... we paid for a plugin and all Trent or whatever (the main dev) says is

"thats not needed"
"we dont handle that"
"that isnt good"

This is seriously starting to get out of hand and very irritating.

https://github.com/drtshock/HCFProblems/issues/91

**Comment by nsporillo** [comment]
I closed it because:
http://puu.sh/gWKWi/1e4c1f7983.png

and I said you could continue discussion there and if we needed to, we can re-open.

You paid for a plugin, yes - that doesnt mean every single [ad hoc](http://puu.sh/gWL2m/1e599891f9.png) request should be added/fixed. Atleast not without sufficient reason to do so. (Regarding #91, the issue at hand is that you want to block interacting with stone pressure plates, but not right clicking-which is interacting. Solving this requires a considerable effort and may introduce other bugs. All in the name of using *splash*-potions on pressure plates. You have to understand that is just a side effect of the intended functionality)

I feel we've been supporting this plugin very well, I've been working nearly everyday to address issues made on the tracker. Just because it was closed doesn't mean it is forgotten. Incase you haven't noticed I'm on the tracker every day, multiple times a day checking for replies to issues. You can still reply to a closed issue and we do re-open them if needed.

There are times when issues don't accurate depict what is needed (in #93, the way it was worded made it seem like we had to do something completely different then what is needed, and that was why I said it was outside the scope of the plugin). Replying quickly to issues has the side effect of making a judgement call too soon. 

I just ask you have a little more patience with the process. I spend a good chunk of my day improving the plugin for your server, for a fraction of the cost of what it would have costed to have it done just for you the correct way.

**Comment by drtshock** [comment]
*Using* a pressure plate is the action of *using* something as is opening a door or ANYTHING else like that. If you want to disable the damage for it, there is already a config option for it as I explained on another ticket. I'd link it but you open so damn many that it's hard to keep track of which is which.
