### ISSUE TITLE
./f show bug

### ISSUE THREAD

**Issue by TMNetwork** [drtshock/HCFProblems#96]
When you do /f show {name}

It doesn't show the members offline.

Proof: 
http://i.imgur.com/Si2WZGx.png

Config:
http://hastebin.com/winidofawo.xml

**Comment by nsporillo** [comment]
This is not a bug. I recommend you read the patch notes for builds so you know exactly what changed. I've been putting in very important information regarding builds there since there isnt really any other place for me to do so. 

What happened was a new config variable was added that defaults to true, but since you're on an older config, it did not show.

What happens if it's enabled is it wont bother sending a line of the f show if the contents are empty.
- no members offline? skip the line
- faction home not set? skip the line
etc

You can disable this in config. It is `hide-unused-fshow`, do:

    hide-unused-fshow: false

You dont *need* to regen a config, you can just paste the above in there at any place.

**Comment by TMNetwork** [comment]
@nsporillo in the .yml or .json?

**Comment by nsporillo** [comment]
We recommend you take backups of your config (can just make a duplicate and set it to another name) so you can regen your config at any time and copy over values you want to stay.

We will not be adding config breaking changes once we start pushing releases. (Everyone is using dev. builds right now). If we do we'll add methods which automatically add what changed into the config for you.

**Comment by nsporillo** [comment]
@TMNetwork in the config.yml

**Comment by TMNetwork** [comment]
Still doesn't work
@nsporillo 
http://hastebin.com/ziyilaxato.rb

**Comment by TMNetwork** [comment]
You see....
@nsporillo

**Comment by TMNetwork** [comment]
@drtshock @nsporillo this isn't fixed... reopen

**Comment by nsporillo** [comment]
@TMNetwork what build are you using? /f version

I just tested and it worked as expected. We'll re-open if it is actually an issue (in the code), not a support ticket

**Comment by TMNetwork** [comment]
@nsporillo Build:
http://i.imgur.com/Inj4fWo.png

**Comment by TMNetwork** [comment]
nvm fixed it @nsporillo

**Comment by nsporillo** [comment]
@TMNetwork what was the fix?

I just noticed that if we hide unused f show and there is someone offline, they dont get shown. That is a bug, it might be related to what you had..?

**Comment by TMNetwork** [comment]
@nsporillo I put 2 extra spaces.
